Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
scrape_liputan(3)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-3-6b41b7c2a9a1>[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m [0mscrape_liputan[0m[0;34m([0m[0;36m3[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m<ipython-input-2-74ee627c229c>[0m in [0;36mscrape_liputan[0;34m(hal)[0m
[1;32m      7[0m         [0msop[0m [0;34m=[0m [0mbs[0m[0;34m([0m[0mge[0m[0;34m,[0m[0;34m'lxml'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m         [0mli[0m [0;34m=[0m [0msop[0m[0;34m.[0m[0mfind[0m[0;34m([0m[0;34m'div'[0m[0;34m,[0m[0mclass_[0m[0;34m=[0m[0;34m'list media_rows list-berita'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m         [0mlin[0m [0;34m=[0m [0mli[0m[0;34m.[0m[0mfind_all[0m[0;34m([0m[0;34m'article'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     10[0m         [0;32mfor[0m [0mx[0m [0;32min[0m [0mlin[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     11[0m             [0mlink[0m [0;34m=[0m [0mx[0m[0;34m.[0m[0mfind[0m[0;34m([0m[0;34m'a'[0m[0;34m)[0m[0;34m[[0m[0;34m'href'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'NoneType' object has no attribute 'find_all'

